inventory:
  build: .
  command: npm start
  ports:
    - "3000:3000"
  links:
    - redis
  environment:
    - NODE_ENV=production
    - REDIS_URL=redis

redis:
  image: redis:latest
  ports:
    - "6379:6379"
